### PR TITLE
allow more liberal names

### PR DESCRIPTION
**Pull request by csabahruska**
allow missing group names
support spaced object names
support spaced material names

### CODE REVIEW

**Comment by csabahruska** [comment]
it seems that missing group/object name fix is still incomplete, because the parser requires a space after the g/o token, which is quite ugly.

**Comment by phaazon** [comment]
Well I guess it’s possible to get rid of the space. I’m on holidays right now, I’ll try to merge and test that as soon as I can :).

**Comment by csabahruska** [comment]
ping

**Comment by phaazon** [comment]
Hi. Sorry, I totally forgot about that! I’ll review it and merge it tonight.

**Comment by phaazon** [comment]
Ok, I tested on a file, it seems to work. I think I should write tests and coverage for that instead of doing that kind of crappy test stuff… Anyway, thanks for the patch, I’ll push to hackage.

**Pull request merged**
